###

GET http://localhost:3000/v1/users HTTP/1.1

###

GET http://localhost:3000/v1/users?name=Dolor HTTP/1.1

###

GET http://localhost:3000/v1/users/1 HTTP/1.1

###

POST http://localhost:3000/v1/users HTTP/1.1

{
    "name": "Lorem Ipsum"
}

###

POST http://localhost:3000/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": null
}

###

PUT http://localhost:3000/v1/users/1 HTTP/1.1

{
    "name": "Lorem Ipsum"
}

###

DELETE http://localhost:3000/v1/users/1 HTTP/1.1
