name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username neutralize --password-stdin
    - name: Build the Docker image :latest
      run: docker build . --file Dockerfile --tag neutralize/mock-server
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag neutralize/mock-server:${{ github.event.release.tag_name }}
    - name: Push the Docker image :latest
      run: docker push neutralize/mock-server
    - name: Push the Docker image
      run: docker push neutralize/mock-server:${{ github.event.release.tag_name }}
